# Generated by Django 4.0.5 on 2022-07-08 10:58

from django.db import migrations, models
import django.db.models.deletion
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_options_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
        ),
    ]
